/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "woaxjupwpkoyjlbjhwmn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvYXhqdXB3cGtveWpsYmpod21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTgyOTgsImV4cCI6MjA2ODk5NDI5OH0.eygL1Ya8lRXRcZjyLy-I3hJ8t6me3RFCZMH3cf9Ol-I"